import type { RouteRecordRaw } from 'vue-router'

export const legacyPathToVuePath: Record<string, string> = {
  '/admin': '/',
  '/admin/': '/',
  '/admin/tasks': '/tasks',
  '/admin/templates': '/templates',
  '/admin/results': '/results',
  '/admin/xpl-analysis-jobs': '/xpl-analysis-jobs',
  '/admin/model-summary': '/model-summary',
  '/admin/scheduler': '/scheduler',
  '/admin/config': '/system/config',
  '/admin/google-sheets': '/system/google-sheets',
  '/admin/navigation': '/system/navigation',
  '/admin/logs': '/system/logs',
  '/admin/users': '/system/users',
  '/admin/roles': '/system/roles',
  '/google-sheet/?version=c3': '/google-sheet/c3/tasks',
  '/google-sheet/?version=c4': '/google-sheet/c4/tasks',
  '/google-sheet/?version=c5': '/google-sheet/c5/tasks',
  '/google-sheet/?version=c7': '/google-sheet/c7/tasks',
  '/backtest-training/list': '/backtest/training/tasks',
  '/backtest-training/create': '/backtest/training/create',
  '/backtest-multi-product/list': '/backtest/multi-product/tasks',
  '/backtest-multi-product/create': '/backtest/multi-product/create',
  '/xpl': '/xpl',
  '/xpl/v1': '/xpl/v1',
}

export const migrationPlaceholderRoutes: RouteRecordRaw[] = [
  { path: 'system/config', name: 'SystemConfig', component: () => import('../pages/system/ConfigView.vue'), meta: { title: '系统配置', navPath: '/admin/config', permission: 'config:view' } },
  { path: 'system/google-sheets', name: 'GoogleSheets', component: () => import('../pages/system/GoogleSheetsView.vue'), meta: { title: 'Google Sheet 管理', navPath: '/admin/google-sheets', permission: 'google_sheet:view' } },
  { path: 'system/navigation', name: 'Navigation', component: () => import('../pages/system/NavigationView.vue'), meta: { title: '路由表管理', navPath: '/admin/navigation', permission: 'navigation:view' } },
  { path: 'system/logs', name: 'Logs', component: () => import('../pages/system/LogView.vue'), meta: { title: '系统日志', navPath: '/admin/logs', permission: 'config:view' } },
  { path: 'system/users', name: 'Users', component: () => import('../pages/system/UserView.vue'), meta: { title: '用户管理', navPath: '/admin/users', permission: 'user:view' } },
  { path: 'system/roles', name: 'Roles', component: () => import('../pages/system/RoleView.vue'), meta: { title: '角色管理', navPath: '/admin/roles', permission: 'user:view' } },
  { path: 'google-sheet/c3/tasks', name: 'C3Tasks', component: () => import('../pages/google-sheet/C3TaskListView.vue'), meta: { title: 'Google Sheet C3', navPath: '/google-sheet/?version=c3' } },
  { path: 'google-sheet/c4/tasks', name: 'C4Tasks', component: () => import('../pages/google-sheet/C4TaskListView.vue'), meta: { title: 'Google Sheet C4', navPath: '/google-sheet/?version=c4' } },
  { path: 'google-sheet/c5/tasks', name: 'C5Tasks', component: () => import('../pages/google-sheet/C5TaskListView.vue'), meta: { title: 'Google Sheet C5', navPath: '/google-sheet/?version=c5' } },
  { path: 'google-sheet/c7/tasks', name: 'C7Tasks', component: () => import('../pages/google-sheet/C7TaskListView.vue'), meta: { title: 'Google Sheet C7', navPath: '/google-sheet/?version=c7' } },
  { path: 'google-sheet/c3/create', name: 'C3TaskCreate', component: () => import('../pages/google-sheet/C3TaskCreateView.vue'), meta: { title: '创建 C3 任务' } },
  { path: 'google-sheet/c31/create', name: 'C31TaskCreate', component: () => import('../pages/google-sheet/C31TaskCreateView.vue'), meta: { title: '创建 C31 批量任务' } },
  { path: 'google-sheet/c4/create', name: 'C4TaskCreate', component: () => import('../pages/google-sheet/C4TaskCreateView.vue'), meta: { title: '创建 C4 任务' } },
  { path: 'google-sheet/c5/create', name: 'C5TaskCreate', component: () => import('../pages/google-sheet/C5TaskCreateView.vue'), meta: { title: '创建 C5 任务' } },
  { path: 'google-sheet/c7/create', name: 'C7TaskCreate', component: () => import('../pages/google-sheet/C7TaskCreateView.vue'), meta: { title: '创建 C7 任务' } },
  { path: 'google-sheet/c3/tasks/:taskId', name: 'C3TaskDetail', component: () => import('../pages/google-sheet/C3TaskDetailView.vue'), meta: { title: 'C3 任务详情' } },
  { path: 'google-sheet/c4/tasks/:taskId', name: 'C4TaskDetail', component: () => import('../pages/google-sheet/C4TaskDetailView.vue'), meta: { title: 'C4 任务详情' } },
  { path: 'google-sheet/c5/tasks/:taskId', name: 'C5TaskDetail', component: () => import('../pages/google-sheet/C5TaskDetailView.vue'), meta: { title: 'C5 任务详情' } },
  { path: 'google-sheet/c7/tasks/:taskId', name: 'C7TaskDetail', component: () => import('../pages/google-sheet/C7TaskDetailView.vue'), meta: { title: 'C7 任务详情' } },
  { path: 'google-sheet/merge-export', name: 'MergeExport', component: () => import('../pages/google-sheet/MergeExportView.vue'), meta: { title: '合并导出' } },
  { path: 'backtest/training/tasks', name: 'BacktestTrainingTasks', component: () => import('../pages/backtest-training/BacktestTrainingListView.vue'), meta: { title: '单品数据回测', navPath: '/backtest-training/list' } },
  { path: 'backtest/training/create', name: 'BacktestTrainingCreate', component: () => import('../pages/backtest-training/BacktestTrainingCreateView.vue'), meta: { title: '创建单品回测' } },
  { path: 'backtest/training/tasks/:taskId', name: 'BacktestTrainingDetail', component: () => import('../pages/backtest-training/BacktestTrainingDetailView.vue'), meta: { title: '单品回测详情' } },
  { path: 'backtest/training/tasks/:taskId/global-preview', name: 'BacktestTrainingGlobalPreview', component: () => import('../pages/backtest-training/BacktestTrainingGlobalPreviewView.vue'), meta: { title: '单品回测全局预览' } },
  { path: 'backtest/training/tasks/:taskId/results/:resultId', name: 'BacktestTrainingResult', component: () => import('../pages/backtest-training/BacktestTrainingResultView.vue'), meta: { title: '单品回测结果' } },
  { path: 'backtest/training/tasks/:taskId/results/:resultId/export-preview', name: 'BacktestTrainingResultExportPreview', component: () => import('../pages/backtest-training/BacktestTrainingResultExportPreviewView.vue'), meta: { title: '单品回测导出预览' } },
  { path: 'backtest/multi-product/tasks', name: 'BacktestMultiProductTasks', component: () => import('../pages/backtest-multi-product/BacktestMultiProductListView.vue'), meta: { title: '多品数据回测', navPath: '/backtest-multi-product/list' } },
  { path: 'backtest/multi-product/create', name: 'BacktestMultiProductCreate', component: () => import('../pages/backtest-multi-product/BacktestMultiProductCreateView.vue'), meta: { title: '创建多品回测' } },
  { path: 'backtest/multi-product/tasks/:taskId', name: 'BacktestMultiProductDetail', component: () => import('../pages/backtest-multi-product/BacktestMultiProductDetailView.vue'), meta: { title: '多品回测详情' } },
  { path: 'backtest/multi-product/tasks/:taskId/global-preview', name: 'BacktestMultiProductGlobalPreview', component: () => import('../pages/backtest-multi-product/BacktestMultiProductGlobalPreviewView.vue'), meta: { title: '多品回测全局预览' } },
  { path: 'backtest/multi-product/tasks/:taskId/results/:resultId', name: 'BacktestMultiProductResult', component: () => import('../pages/backtest-multi-product/BacktestMultiProductResultView.vue'), meta: { title: '多品回测结果' } },
  { path: 'xpl', name: 'XplIndex', component: () => import('../pages/xpl/XplIndexView.vue'), meta: { title: '夏普率计算', navPath: '/xpl' } },
  { path: 'xpl/v1', name: 'XplV1Analysis', component: () => import('../pages/xpl/XplV1AnalysisView.vue'), meta: { title: 'V1 回测数据分析', navPath: '/xpl/v1' } },
  { path: 'yule', name: 'YuleIndex', component: () => import('../pages/yule/YuleIndexView.vue'), meta: { title: '娱乐工具' } },
  { path: 'yule/data-download', name: 'YuleDataDownload', component: () => import('../pages/yule/YuleDataDownloadView.vue'), meta: { title: '数据下载' } },
]
