name: google-sheet-validator

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: google_task:1.0.4
    restart: unless-stopped
    init: true
    ports:
      - "8081:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      APP_ENV: production
      FLASK_DEBUG: "false"
    user: "1000:1000"  # 添加这一行，使用普通用户运行
    stop_grace_period: 45s
